import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bukenoff development</title>
        <meta name="description" content="Generated by my feeling of boredom" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my site
        </h1>

        <p className={styles.description}>
          There is nothing to look at currently
        </p>
      </main>

      <footer className={styles.footer}>
        this is a footer
      </footer>
    </div>
  )
}

export default Home
